-- F02 units and rooms. Generated by prisma migrate diff, plus hand-written parts at the end.

-- CreateTable
CREATE TABLE "unit" (
    "id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "name" VARCHAR(80) NOT NULL,
    "cnpj" CHAR(14),
    "time_zone" VARCHAR(64) NOT NULL,
    "phone" VARCHAR(11),
    "email" VARCHAR(254),
    "cep" CHAR(8),
    "street" VARCHAR(150),
    "number" VARCHAR(20),
    "complement" VARCHAR(80),
    "district" VARCHAR(80),
    "city" VARCHAR(80),
    "state" CHAR(2),
    "active" BOOLEAN NOT NULL DEFAULT true,
    "version" INTEGER NOT NULL DEFAULT 1,
    "created_by_id" UUID,
    "updated_by_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "unit_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "unit_business_hours" (
    "id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "unit_id" UUID NOT NULL,
    "weekday" SMALLINT NOT NULL,
    "start_minute" SMALLINT NOT NULL,
    "end_minute" SMALLINT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "unit_business_hours_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "unit_closure" (
    "id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "unit_id" UUID NOT NULL,
    "starts_on" DATE NOT NULL,
    "ends_on" DATE NOT NULL,
    "reason" VARCHAR(120) NOT NULL,
    "created_by_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "unit_closure_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "room" (
    "id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "unit_id" UUID NOT NULL,
    "name" VARCHAR(50) NOT NULL,
    "description" VARCHAR(200),
    "active" BOOLEAN NOT NULL DEFAULT true,
    "version" INTEGER NOT NULL DEFAULT 1,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "room_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "unit_selection" (
    "user_id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "unit_id" UUID NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "unit_selection_pkey" PRIMARY KEY ("user_id")
);

-- CreateIndex
CREATE INDEX "ix_unit_org_active" ON "unit"("organization_id", "active");

-- CreateIndex
CREATE INDEX "ix_ubh_unit_weekday" ON "unit_business_hours"("unit_id", "weekday");

-- CreateIndex
CREATE INDEX "ix_closure_unit_period" ON "unit_closure"("unit_id", "ends_on", "starts_on");

-- CreateIndex
CREATE INDEX "ix_room_unit_active" ON "room"("unit_id", "active");

-- AddForeignKey
ALTER TABLE "unit" ADD CONSTRAINT "fk_unit_org" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "unit_business_hours" ADD CONSTRAINT "fk_ubh_unit" FOREIGN KEY ("unit_id") REFERENCES "unit"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "unit_closure" ADD CONSTRAINT "fk_closure_unit" FOREIGN KEY ("unit_id") REFERENCES "unit"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "room" ADD CONSTRAINT "fk_room_unit" FOREIGN KEY ("unit_id") REFERENCES "unit"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "unit_selection" ADD CONSTRAINT "fk_unit_selection_user" FOREIGN KEY ("user_id") REFERENCES "app_user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "unit_selection" ADD CONSTRAINT "fk_unit_selection_unit" FOREIGN KEY ("unit_id") REFERENCES "unit"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- hand-written: case-insensitive unique names (spec F02 section 6)
CREATE UNIQUE INDEX "uq_unit_org_name" ON "unit" ("organization_id", lower("name"));
CREATE UNIQUE INDEX "uq_room_unit_name" ON "room" ("unit_id", lower("name"));

-- hand-written: value constraints
ALTER TABLE "unit" ADD CONSTRAINT "ck_unit_cnpj" CHECK ("cnpj" ~ '^[0-9A-Z]{12}[0-9]{2}$');
ALTER TABLE "unit" ADD CONSTRAINT "ck_unit_cep" CHECK ("cep" ~ '^[0-9]{8}$');
ALTER TABLE "unit" ADD CONSTRAINT "ck_unit_phone" CHECK ("phone" ~ '^[0-9]{10,11}$');
ALTER TABLE "unit" ADD CONSTRAINT "ck_unit_state" CHECK ("state" ~ '^[A-Z]{2}$');
ALTER TABLE "unit_business_hours" ADD CONSTRAINT "ck_ubh_weekday" CHECK ("weekday" BETWEEN 1 AND 7);
ALTER TABLE "unit_business_hours" ADD CONSTRAINT "ck_ubh_range"
  CHECK ("start_minute" >= 0 AND "end_minute" <= 1440 AND "start_minute" < "end_minute");
ALTER TABLE "unit_business_hours" ADD CONSTRAINT "ck_ubh_granularity"
  CHECK ("start_minute" % 5 = 0 AND "end_minute" % 5 = 0);
ALTER TABLE "unit_closure" ADD CONSTRAINT "ck_closure_range"
  CHECK ("ends_on" >= "starts_on" AND "ends_on" <= "starts_on" + 366);
