-- F05 patient registry. Generated by prisma migrate diff, plus hand-written parts at the end.

-- CreateTable
CREATE TABLE "patient" (
    "id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "full_name" VARCHAR(150) NOT NULL,
    "social_name" VARCHAR(150),
    "normalized_name" VARCHAR(150) NOT NULL,
    "birth_date" DATE NOT NULL,
    "sex" VARCHAR(12) NOT NULL DEFAULT 'NOT_INFORMED',
    "cpf" CHAR(11),
    "rg" VARCHAR(20),
    "mobile_phone" VARCHAR(11) NOT NULL,
    "secondary_phone" VARCHAR(11),
    "phone_digits" VARCHAR(23) NOT NULL,
    "email" VARCHAR(254),
    "cep" CHAR(8),
    "street" VARCHAR(150),
    "number" VARCHAR(20),
    "complement" VARCHAR(80),
    "district" VARCHAR(80),
    "city" VARCHAR(80),
    "state" CHAR(2),
    "occupation" VARCHAR(80),
    "referral_source_id" UUID,
    "observations" VARCHAR(2000),
    "guardian_name" VARCHAR(150),
    "guardian_cpf" CHAR(11),
    "guardian_relationship" VARCHAR(20),
    "guardian_phone" VARCHAR(11),
    "active" BOOLEAN NOT NULL DEFAULT true,
    "inactive_reason" VARCHAR(12),
    "inactive_note" VARCHAR(200),
    "deactivated_at" TIMESTAMPTZ(6),
    "version" INTEGER NOT NULL DEFAULT 1,
    "created_by_id" UUID,
    "updated_by_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "patient_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "referral_source" (
    "id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "name" VARCHAR(40) NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "sort_order" SMALLINT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "referral_source_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tag" (
    "id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "name" VARCHAR(40) NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "sort_order" SMALLINT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "tag_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "patient_tag" (
    "patient_id" UUID NOT NULL,
    "tag_id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,

    CONSTRAINT "pk_patient_tag" PRIMARY KEY ("patient_id","tag_id")
);

-- CreateTable
CREATE TABLE "privacy_terms_version" (
    "id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "version" INTEGER NOT NULL,
    "text" TEXT NOT NULL,
    "published_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "published_by_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "privacy_terms_version_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "consent_record" (
    "id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "patient_id" UUID NOT NULL,
    "terms_version_id" UUID NOT NULL,
    "consented_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "method" VARCHAR(16) NOT NULL,
    "recorded_by_id" UUID NOT NULL,
    "file_object_key" VARCHAR(255),
    "file_name" VARCHAR(150),
    "file_size" INTEGER,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "consent_record_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "consent_upload" (
    "id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "object_key" VARCHAR(255) NOT NULL,
    "file_name" VARCHAR(150) NOT NULL,
    "file_size" INTEGER NOT NULL,
    "content_type" VARCHAR(40) NOT NULL,
    "uploaded_by_id" UUID NOT NULL,
    "consumed_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "consent_upload_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "ix_patient_org_identity" ON "patient"("organization_id", "normalized_name", "birth_date");

-- CreateIndex
CREATE INDEX "ix_patient_org_active_name" ON "patient"("organization_id", "active", "normalized_name");

-- CreateIndex
CREATE INDEX "ix_referral_source_org_order" ON "referral_source"("organization_id", "sort_order");

-- CreateIndex
CREATE INDEX "ix_tag_org_order" ON "tag"("organization_id", "sort_order");

-- CreateIndex
CREATE INDEX "ix_patient_tag_tag" ON "patient_tag"("tag_id");

-- CreateIndex
CREATE UNIQUE INDEX "uq_terms_org_version" ON "privacy_terms_version"("organization_id", "version");

-- CreateIndex
CREATE INDEX "ix_consent_patient_time" ON "consent_record"("patient_id", "consented_at" DESC);

-- AddForeignKey
ALTER TABLE "patient" ADD CONSTRAINT "fk_patient_org" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "patient" ADD CONSTRAINT "fk_patient_referral_source" FOREIGN KEY ("referral_source_id") REFERENCES "referral_source"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "patient_tag" ADD CONSTRAINT "fk_patient_tag_patient" FOREIGN KEY ("patient_id") REFERENCES "patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "patient_tag" ADD CONSTRAINT "fk_patient_tag_tag" FOREIGN KEY ("tag_id") REFERENCES "tag"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "consent_record" ADD CONSTRAINT "fk_consent_patient" FOREIGN KEY ("patient_id") REFERENCES "patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "consent_record" ADD CONSTRAINT "fk_consent_terms" FOREIGN KEY ("terms_version_id") REFERENCES "privacy_terms_version"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- hand-written: CPF unique within the organization (PRD F05)
CREATE UNIQUE INDEX "uq_patient_org_cpf" ON "patient" ("organization_id", "cpf") WHERE "cpf" IS NOT NULL;

-- hand-written: search by partial name and by phone digits (PRD F05: p95 <= 1 s with 100k patients)
CREATE INDEX "ix_patient_name_trgm" ON "patient" USING gin ("normalized_name" gin_trgm_ops);
CREATE INDEX "ix_patient_phone_trgm" ON "patient" USING gin ("phone_digits" gin_trgm_ops);

-- hand-written: case-insensitive unique names in the configurable lists
CREATE UNIQUE INDEX "uq_tag_org_name" ON "tag" ("organization_id", lower("name"));
CREATE UNIQUE INDEX "uq_referral_source_org_name" ON "referral_source" ("organization_id", lower("name"));

-- hand-written: pending uploads for the cleanup job
CREATE INDEX "ix_consent_upload_pending" ON "consent_upload" ("created_at") WHERE "consumed_at" IS NULL;

-- hand-written: value constraints (PRD F05 capabilities)
ALTER TABLE "patient" ADD CONSTRAINT "ck_patient_sex" CHECK ("sex" IN ('FEMALE', 'MALE', 'OTHER', 'NOT_INFORMED'));
ALTER TABLE "patient" ADD CONSTRAINT "ck_patient_cpf" CHECK ("cpf" ~ '^[0-9]{11}$');
ALTER TABLE "patient" ADD CONSTRAINT "ck_patient_guardian_cpf" CHECK ("guardian_cpf" ~ '^[0-9]{11}$');
ALTER TABLE "patient" ADD CONSTRAINT "ck_patient_mobile" CHECK ("mobile_phone" ~ '^[0-9]{2}9[0-9]{8}$');
ALTER TABLE "patient" ADD CONSTRAINT "ck_patient_secondary" CHECK ("secondary_phone" ~ '^[0-9]{10,11}$');
ALTER TABLE "patient" ADD CONSTRAINT "ck_patient_guardian_relationship" CHECK (
  "guardian_relationship" IN ('MOTHER', 'FATHER', 'GRANDPARENT', 'LEGAL_GUARDIAN', 'OTHER'));
ALTER TABLE "patient" ADD CONSTRAINT "ck_patient_guardian_complete" CHECK (
  ("guardian_name" IS NULL AND "guardian_relationship" IS NULL AND "guardian_phone" IS NULL)
  OR ("guardian_name" IS NOT NULL AND "guardian_relationship" IS NOT NULL AND "guardian_phone" IS NOT NULL));
ALTER TABLE "patient" ADD CONSTRAINT "ck_patient_inactive_reason" CHECK (
  "inactive_reason" IN ('DECEASED', 'MOVED', 'OTHER'));
ALTER TABLE "patient" ADD CONSTRAINT "ck_patient_inactive" CHECK ("active" OR "inactive_reason" IS NOT NULL);
ALTER TABLE "consent_record" ADD CONSTRAINT "ck_consent_method" CHECK (
  "method" IN ('PAPER_UPLOADED', 'VERBAL', 'DIGITAL'));
ALTER TABLE "privacy_terms_version" ADD CONSTRAINT "ck_terms_version" CHECK ("version" >= 1);

-- hand-written: consent and terms are legal evidence (LGPD); the runtime role may only append and read.
REVOKE ALL ON "privacy_terms_version", "consent_record" FROM gcli_app;
GRANT SELECT, INSERT ON "privacy_terms_version", "consent_record" TO gcli_app;
