import { DOCUMENT_SPECS } from "../documents";
import { TAX_ID_SPECS } from "../tax-id";
import type { CountryProfile, Region } from "./types";

// ISO 3166-2:ES province codes.
export const SPAIN_PROVINCES: readonly Region[] = [
  { code: "C", name: "A Coruña" },
  { code: "VI", name: "Álava" },
  { code: "AB", name: "Albacete" },
  { code: "A", name: "Alicante" },
  { code: "AL", name: "Almería" },
  { code: "O", name: "Asturias" },
  { code: "AV", name: "Ávila" },
  { code: "BA", name: "Badajoz" },
  { code: "PM", name: "Illes Balears" },
  { code: "B", name: "Barcelona" },
  { code: "BI", name: "Bizkaia" },
  { code: "BU", name: "Burgos" },
  { code: "CC", name: "Cáceres" },
  { code: "CA", name: "Cádiz" },
  { code: "S", name: "Cantabria" },
  { code: "CS", name: "Castellón" },
  { code: "CE", name: "Ceuta" },
  { code: "CR", name: "Ciudad Real" },
  { code: "CO", name: "Córdoba" },
  { code: "CU", name: "Cuenca" },
  { code: "GI", name: "Girona" },
  { code: "GR", name: "Granada" },
  { code: "GU", name: "Guadalajara" },
  { code: "SS", name: "Gipuzkoa" },
  { code: "H", name: "Huelva" },
  { code: "HU", name: "Huesca" },
  { code: "J", name: "Jaén" },
  { code: "LO", name: "La Rioja" },
  { code: "GC", name: "Las Palmas" },
  { code: "LE", name: "León" },
  { code: "L", name: "Lleida" },
  { code: "LU", name: "Lugo" },
  { code: "M", name: "Madrid" },
  { code: "MA", name: "Málaga" },
  { code: "ML", name: "Melilla" },
  { code: "MU", name: "Murcia" },
  { code: "NA", name: "Navarra" },
  { code: "OR", name: "Ourense" },
  { code: "P", name: "Palencia" },
  { code: "PO", name: "Pontevedra" },
  { code: "SA", name: "Salamanca" },
  { code: "TF", name: "Santa Cruz de Tenerife" },
  { code: "SG", name: "Segovia" },
  { code: "SE", name: "Sevilla" },
  { code: "SO", name: "Soria" },
  { code: "T", name: "Tarragona" },
  { code: "TE", name: "Teruel" },
  { code: "TO", name: "Toledo" },
  { code: "V", name: "Valencia" },
  { code: "VA", name: "Valladolid" },
  { code: "ZA", name: "Zamora" },
  { code: "Z", name: "Zaragoza" },
];

const college = (type: string) => ({
  type,
  labelKey: `countries.councils.${type}`,
  // The provincial college that issued the registration.
  regionRequired: true,
  regions: SPAIN_PROVINCES,
});

export const ES: CountryProfile = {
  code: "ES",
  nameKey: "countries.names.ES",
  currency: "EUR",
  formattingRegion: "es-ES",
  phoneCode: "34",
  // Mobile numbers start with 6 or 7.
  mobilePattern: /^[67]\d{8}$/,
  timeZones: ["Europe/Madrid", "Atlantic/Canary", "Africa/Ceuta"],
  defaultTimeZone: "Europe/Madrid",
  taxId: TAX_ID_SPECS.NIF_ES,
  identityDocuments: [DOCUMENT_SPECS.DNI_ES, DOCUMENT_SPECS.NIE_ES],
  address: {
    fields: [
      { name: "street", labelKey: "countries.address.street", required: false },
      { name: "number", labelKey: "countries.address.number", required: false },
      { name: "complement", labelKey: "countries.address.complement", required: false },
      { name: "city", labelKey: "countries.address.city", required: false },
    ],
    postalCode: {
      labelKey: "countries.address.postalCodeLabel.default",
      pattern: /^\d{5}$/,
      required: false,
      normalize: (input) => input.replace(/\D/g, "").slice(0, 5),
      format: (value) => value,
    },
    region: { labelKey: "countries.address.regionLabel.ES", required: false, regions: SPAIN_PROVINCES },
  },
  councils: [
    college("COLEGIO_MEDICOS"),
    college("COLEGIO_ENFERMERIA"),
    college("COLEGIO_PSICOLOGOS"),
    college("COLEGIO_ODONTOLOGOS"),
    college("COLEGIO_FARMACEUTICOS"),
    college("COLEGIO_FISIOTERAPEUTAS"),
    college("COLEGIO_NUTRICIONISTAS"),
    { type: "OTHER", labelKey: "countries.councils.OTHER", regionRequired: false, needsName: true },
  ],
  paymentMethods: ["CASH", "BIZUM", "DEBIT_CARD", "CREDIT_CARD", "TRANSFER", "OTHER"],
  legalRulesValidated: false,
};
