-- F01 foundation schema. Generated by prisma migrate diff, plus hand-written parts marked "hand-written".
-- Runs as the owner role (DATABASE_MIGRATION_URL). The runtime role gcli_app must already exist.

-- hand-written: fail early with a clear message when the runtime role is missing
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'gcli_app') THEN
    RAISE EXCEPTION 'Role gcli_app is missing. Create it before running migrations (see docker/postgres/init/01-roles.sql).';
  END IF;
END $$;

-- hand-written: every table the owner creates is usable (DML) by the runtime role
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO gcli_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO gcli_app;

-- hand-written: extensions used by search features (F05 and later)
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;

-- CreateTable
CREATE TABLE "organization" (
    "id" UUID NOT NULL,
    "legal_name" VARCHAR(150) NOT NULL,
    "trade_name" VARCHAR(150),
    "cnpj" CHAR(14),
    "logo_object_key" VARCHAR(255),
    "logo_version" INTEGER NOT NULL DEFAULT 0,
    "time_zone" VARCHAR(64) NOT NULL DEFAULT 'America/Sao_Paulo',
    "slot_granularity_minutes" SMALLINT NOT NULL DEFAULT 15,
    "version" INTEGER NOT NULL DEFAULT 1,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by_id" UUID,

    CONSTRAINT "organization_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app_user" (
    "id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "name" VARCHAR(150) NOT NULL,
    "email" VARCHAR(254) NOT NULL,
    "email_verified" BOOLEAN NOT NULL DEFAULT false,
    "image" VARCHAR(255),
    "role" VARCHAR(20) NOT NULL,
    "status" VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    "failed_login_count" SMALLINT NOT NULL DEFAULT 0,
    "locked_until" TIMESTAMPTZ(6),
    "last_login_at" TIMESTAMPTZ(6),
    "deactivated_at" TIMESTAMPTZ(6),
    "version" INTEGER NOT NULL DEFAULT 1,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "app_user_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "session" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "token" VARCHAR(255) NOT NULL,
    "expires_at" TIMESTAMPTZ(6) NOT NULL,
    "last_active_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ip_address" VARCHAR(45),
    "user_agent" VARCHAR(512),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "session_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "account" (
    "id" UUID NOT NULL,
    "account_id" VARCHAR(255) NOT NULL,
    "provider_id" VARCHAR(50) NOT NULL,
    "user_id" UUID NOT NULL,
    "access_token" TEXT,
    "refresh_token" TEXT,
    "id_token" TEXT,
    "access_token_expires_at" TIMESTAMPTZ(6),
    "refresh_token_expires_at" TIMESTAMPTZ(6),
    "scope" TEXT,
    "password" VARCHAR(255),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "account_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "verification" (
    "id" UUID NOT NULL,
    "identifier" VARCHAR(255) NOT NULL,
    "value" TEXT NOT NULL,
    "expires_at" TIMESTAMPTZ(6) NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "verification_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "invitation" (
    "id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "email" VARCHAR(254) NOT NULL,
    "name" VARCHAR(150) NOT NULL,
    "role" VARCHAR(20) NOT NULL,
    "token_hash" CHAR(64) NOT NULL,
    "status" VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    "expires_at" TIMESTAMPTZ(6) NOT NULL,
    "invited_by_id" UUID,
    "accepted_user_id" UUID,
    "accepted_at" TIMESTAMPTZ(6),
    "revoked_at" TIMESTAMPTZ(6),
    "resend_count" SMALLINT NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "invitation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "rate_limit_bucket" (
    "key" VARCHAR(200) NOT NULL,
    "count" INTEGER NOT NULL DEFAULT 0,
    "window_started_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "blocked_until" TIMESTAMPTZ(6),

    CONSTRAINT "rate_limit_bucket_pkey" PRIMARY KEY ("key")
);

-- CreateTable
CREATE TABLE "outbox_message" (
    "id" UUID NOT NULL,
    "organization_id" UUID,
    "type" VARCHAR(80) NOT NULL,
    "payload" JSONB NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "dispatched_at" TIMESTAMPTZ(6),
    "attempts" SMALLINT NOT NULL DEFAULT 0,
    "last_error" VARCHAR(500),

    CONSTRAINT "outbox_message_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "uq_app_user_email" ON "app_user"("email");

-- CreateIndex
CREATE INDEX "ix_app_user_org_status_role" ON "app_user"("organization_id", "status", "role");

-- CreateIndex
CREATE UNIQUE INDEX "uq_session_token" ON "session"("token");

-- CreateIndex
CREATE INDEX "ix_session_user" ON "session"("user_id");

-- CreateIndex
CREATE INDEX "ix_session_expires" ON "session"("expires_at");

-- CreateIndex
CREATE INDEX "ix_account_user" ON "account"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "uq_account_provider" ON "account"("provider_id", "account_id");

-- CreateIndex
CREATE INDEX "ix_verification_identifier" ON "verification"("identifier");

-- CreateIndex
CREATE UNIQUE INDEX "uq_invitation_token_hash" ON "invitation"("token_hash");

-- CreateIndex
CREATE INDEX "ix_invitation_org_status" ON "invitation"("organization_id", "status");

-- AddForeignKey
ALTER TABLE "app_user" ADD CONSTRAINT "fk_app_user_org" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "session" ADD CONSTRAINT "fk_session_user" FOREIGN KEY ("user_id") REFERENCES "app_user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "account" ADD CONSTRAINT "fk_account_user" FOREIGN KEY ("user_id") REFERENCES "app_user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "invitation" ADD CONSTRAINT "fk_invitation_org" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- hand-written: value constraints (varchar + CHECK instead of native enums, architecture section 6)
ALTER TABLE "organization" ADD CONSTRAINT "ck_organization_slot" CHECK ("slot_granularity_minutes" IN (5, 10, 15, 30));
ALTER TABLE "organization" ADD CONSTRAINT "ck_organization_cnpj" CHECK ("cnpj" ~ '^[0-9A-Z]{12}[0-9]{2}$');
ALTER TABLE "app_user" ADD CONSTRAINT "ck_app_user_role" CHECK ("role" IN ('ADMINISTRATOR', 'MANAGER', 'FRONT_DESK', 'PROFESSIONAL'));
ALTER TABLE "app_user" ADD CONSTRAINT "ck_app_user_status" CHECK ("status" IN ('ACTIVE', 'INACTIVE'));
ALTER TABLE "app_user" ADD CONSTRAINT "ck_app_user_email_lower" CHECK ("email" = lower("email"));
ALTER TABLE "invitation" ADD CONSTRAINT "ck_invitation_role" CHECK ("role" IN ('ADMINISTRATOR', 'MANAGER', 'FRONT_DESK', 'PROFESSIONAL'));
ALTER TABLE "invitation" ADD CONSTRAINT "ck_invitation_status" CHECK ("status" IN ('PENDING', 'ACCEPTED', 'REVOKED'));

-- hand-written: at most one pending invitation per email in an organization
CREATE UNIQUE INDEX "uq_invitation_pending_email" ON "invitation" ("organization_id", "email") WHERE "status" = 'PENDING';

-- hand-written: outbox polling index
CREATE INDEX "ix_outbox_pending" ON "outbox_message" ("created_at") WHERE "dispatched_at" IS NULL;

-- hand-written: pg-boss keeps its own tables in a schema owned by the runtime role
CREATE SCHEMA IF NOT EXISTS pgboss AUTHORIZATION gcli_app;
