-- F04 professionals and working hours. Generated by prisma migrate diff, plus hand-written parts at the end.
-- btree_gist is needed by the schedule validity exclusion constraint.
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- CreateTable
CREATE TABLE "professional" (
    "id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "full_name" VARCHAR(150) NOT NULL,
    "display_name" VARCHAR(60),
    "specialty" VARCHAR(100),
    "council_type" VARCHAR(10) NOT NULL DEFAULT 'NONE',
    "council_other_name" VARCHAR(20),
    "council_number" VARCHAR(15),
    "council_state" CHAR(2),
    "cpf" CHAR(11),
    "phone" VARCHAR(11),
    "email" VARCHAR(254),
    "color" VARCHAR(16) NOT NULL,
    "linked_user_id" UUID,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "deactivated_at" TIMESTAMPTZ(6),
    "version" INTEGER NOT NULL DEFAULT 1,
    "created_by_id" UUID,
    "updated_by_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "professional_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "professional_service" (
    "professional_id" UUID NOT NULL,
    "service_id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "pk_professional_service" PRIMARY KEY ("professional_id","service_id")
);

-- CreateTable
CREATE TABLE "professional_schedule" (
    "id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "professional_id" UUID NOT NULL,
    "valid_from" DATE NOT NULL,
    "valid_until" DATE,
    "version" INTEGER NOT NULL DEFAULT 1,
    "created_by_id" UUID,
    "updated_by_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "professional_schedule_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "professional_working_interval" (
    "id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "schedule_id" UUID NOT NULL,
    "unit_id" UUID NOT NULL,
    "weekday" SMALLINT NOT NULL,
    "start_minute" SMALLINT NOT NULL,
    "end_minute" SMALLINT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "professional_working_interval_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "professional_time_off" (
    "id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "professional_id" UUID NOT NULL,
    "type" VARCHAR(12) NOT NULL,
    "starts_at" TIMESTAMPTZ(6) NOT NULL,
    "ends_at" TIMESTAMPTZ(6) NOT NULL,
    "all_day" BOOLEAN NOT NULL DEFAULT false,
    "note" VARCHAR(200),
    "created_by_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "professional_time_off_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "uq_professional_linked_user" ON "professional"("linked_user_id");

-- CreateIndex
CREATE INDEX "ix_professional_org_active" ON "professional"("organization_id", "active");

-- CreateIndex
CREATE INDEX "ix_professional_service_service" ON "professional_service"("service_id");

-- CreateIndex
CREATE INDEX "ix_schedule_professional_period" ON "professional_schedule"("professional_id", "valid_from");

-- CreateIndex
CREATE INDEX "ix_pwi_schedule_weekday" ON "professional_working_interval"("schedule_id", "weekday");

-- CreateIndex
CREATE INDEX "ix_pwi_unit" ON "professional_working_interval"("unit_id");

-- CreateIndex
CREATE INDEX "ix_time_off_professional_period" ON "professional_time_off"("professional_id", "ends_at", "starts_at");

-- AddForeignKey
ALTER TABLE "professional" ADD CONSTRAINT "fk_professional_org" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "professional" ADD CONSTRAINT "fk_professional_linked_user" FOREIGN KEY ("linked_user_id") REFERENCES "app_user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "professional_service" ADD CONSTRAINT "fk_professional_service_professional" FOREIGN KEY ("professional_id") REFERENCES "professional"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "professional_service" ADD CONSTRAINT "fk_professional_service_service" FOREIGN KEY ("service_id") REFERENCES "service"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "professional_schedule" ADD CONSTRAINT "fk_schedule_professional" FOREIGN KEY ("professional_id") REFERENCES "professional"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "professional_working_interval" ADD CONSTRAINT "fk_pwi_schedule" FOREIGN KEY ("schedule_id") REFERENCES "professional_schedule"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "professional_working_interval" ADD CONSTRAINT "fk_pwi_unit" FOREIGN KEY ("unit_id") REFERENCES "unit"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "professional_time_off" ADD CONSTRAINT "fk_time_off_professional" FOREIGN KEY ("professional_id") REFERENCES "professional"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- hand-written: one profile per person and per council registration (spec F04 section 6)
CREATE UNIQUE INDEX "uq_professional_org_cpf" ON "professional" ("organization_id", "cpf")
  WHERE "cpf" IS NOT NULL;
CREATE UNIQUE INDEX "uq_professional_org_council" ON "professional"
  ("organization_id", "council_type", coalesce("council_other_name", ''), "council_state", "council_number")
  WHERE "council_type" <> 'NONE';

-- hand-written: value constraints (PRD F04 capabilities)
ALTER TABLE "professional" ADD CONSTRAINT "ck_professional_council_type" CHECK ("council_type" IN (
  'CRM', 'CRO', 'CREFITO', 'CRP', 'CRN', 'COREN', 'CRBM', 'CRF', 'OTHER', 'NONE'));
-- PRD F04: council number and state are required when the type is not "none".
ALTER TABLE "professional" ADD CONSTRAINT "ck_professional_council" CHECK (
  ("council_type" = 'NONE' AND "council_number" IS NULL AND "council_state" IS NULL
    AND "council_other_name" IS NULL)
  OR ("council_type" <> 'NONE' AND "council_number" IS NOT NULL AND "council_state" IS NOT NULL
    AND (("council_type" = 'OTHER') = ("council_other_name" IS NOT NULL))));
ALTER TABLE "professional" ADD CONSTRAINT "ck_professional_cpf" CHECK ("cpf" ~ '^[0-9]{11}$');
ALTER TABLE "professional" ADD CONSTRAINT "ck_professional_phone" CHECK ("phone" ~ '^[0-9]{10,11}$');
ALTER TABLE "professional" ADD CONSTRAINT "ck_professional_state" CHECK ("council_state" ~ '^[A-Z]{2}$');
ALTER TABLE "professional" ADD CONSTRAINT "ck_professional_color" CHECK ("color" IN (
  'slate', 'red', 'orange', 'amber', 'yellow', 'lime', 'green', 'emerald',
  'teal', 'cyan', 'sky', 'blue', 'indigo', 'violet', 'purple', 'pink'));

-- hand-written: a professional's schedules never overlap in time, even under concurrent saves
ALTER TABLE "professional_schedule" ADD CONSTRAINT "ck_schedule_range"
  CHECK ("valid_until" IS NULL OR "valid_until" >= "valid_from");
ALTER TABLE "professional_schedule" ADD CONSTRAINT "ex_schedule_no_overlap"
  EXCLUDE USING gist ("professional_id" WITH =, daterange("valid_from", "valid_until", '[]') WITH &&);

ALTER TABLE "professional_working_interval" ADD CONSTRAINT "ck_pwi_weekday" CHECK ("weekday" BETWEEN 1 AND 7);
ALTER TABLE "professional_working_interval" ADD CONSTRAINT "ck_pwi_range"
  CHECK ("start_minute" >= 0 AND "end_minute" <= 1440 AND "start_minute" < "end_minute");
ALTER TABLE "professional_working_interval" ADD CONSTRAINT "ck_pwi_granularity"
  CHECK ("start_minute" % 5 = 0 AND "end_minute" % 5 = 0);

ALTER TABLE "professional_time_off" ADD CONSTRAINT "ck_time_off_type"
  CHECK ("type" IN ('VACATION', 'CONFERENCE', 'PERSONAL', 'OTHER'));
ALTER TABLE "professional_time_off" ADD CONSTRAINT "ck_time_off_range"
  CHECK ("ends_at" >= "starts_at" + interval '5 minutes');
